name: Production Deployment
on:
  workflow_dispatch:
    inputs:
      sha:
        description: "Please"
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: install
        run: npm run install

      - name: build
        run: npm run build
